apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstreetmap-tile-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openstreetmap-tile-server.name" . }}
    helm.sh/chart: {{ include "openstreetmap-tile-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "openstreetmap-tile-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
