apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: osrm-backend
    labels:
      run: osrm-backend
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    namespace: default
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/osrm-backend
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          api: osrm-backend
      spec:
        volumes:
          - name: osrm-backend-volume
            persistentVolumeClaim:
              claimName: osrm-pv-claim
        containers:
        - name: osrm-backend
          image: osrm/osrm-backend
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          args:
          - "osrm-routed"
          - "--algorithm"
          - mld
          - "/data/argentina.osrm"
          volumeMounts:
            - mountPath: /data
              name: osrm-backend-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List

