kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
  name: osrm-pv-claim  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "ssd"

