apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    labels:
      run: streetmap
    name: streetmap
    namespace: default
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/streetmap
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: streetmap
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: streetmap
      spec:
        containers:
        - args:
          - run
          image: overv/openstreetmap-tile-server
          imagePullPolicy: Always
          name: streetmap
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
            volumeMounts:
            - mountPath: /var/www/html/ 
              name: openstreetmap
        volumes:
        - name: openstreetmap
          persistentVolumeClaim:
            claimName: task-pv-claim
  status:
    availableReplicas: 1
    conditions:
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
